openapi: 3.0.0
paths:
  /population/composition/perYear:
    parameters: []
    get:
      summary: 人口マップ_人口構成_人口構成
      operationId: api.v1.population.composition.per_year
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  resule:
                    type: object
                    properties:
                      bundaryYear:
                        type: integer
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                            data:
                              type: array
                              items:
                                type: object
                                properties:
                                  year:
                                    type: integer
                                  value:
                                    type: integer
      description: 人口マップ人口構成_人口構成
      parameters:
        - schema:
            type: integer
            minLength: 1
            maxLength: 47
            minimum: 1
            maximum: 47
          in: query
          name: prefCode
          description: 都道府県コード
          required: true
        - schema:
            type: string
            default: '-'
            pattern: '^[0-9]{5}|[-]{1}$'
          in: query
          name: cityCode
          description: 市区町村コード
        - schema:
            type: string
            pattern: '^((([1-9]|[1-3][0-9]|4[0-7])_([0-9]{5})*)[,]?)+$'
          in: query
          name: addArea
          description: 追加エリアコード
components:
  schemas: {}
  securitySchemes: {}
info:
  title: RESAS API
  description: RESAS API
  version: '1.0'
  contact:
    name: ot-nemoto
    url: 'https://github.com/ot-nemoto/resas-api/issues'
    email: nemoto@opentone.co.jp
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000/api/v1'
