openapi: 3.0.0
paths:
  /population/composition/perYear:
    parameters: []
    get:
      summary: 人口構成
      operationId: api.v1.population.composition.per_year
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      bundaryYear:
                        type: integer
                        description: 実績値と推計値の区切り年
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                              enum:
                                - 総人口
                                - 年少人口
                                - 生産年齢人口
                                - 老年人口
                              description: ラベル
                            data:
                              type: array
                              items:
                                type: object
                                properties:
                                  year:
                                    type: integer
                                    description: 年
                                  value:
                                    type: integer
                                    description: 人口
                                  rate:
                                    type: number
                                    description: 割合<br>labelが総人口の場合は存在しません。
              examples: {}
      description: 地域単位、年単位の年齢構成のデータを返します。
      parameters:
        - $ref: '#/components/parameters/prefCode'
        - $ref: '#/components/parameters/cityCode'
        - $ref: '#/components/parameters/addArea'
      tags:
        - 人口マップ / 人口構成
  /population/composition/pyramid:
    get:
      summary: 人口ピラミッド
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      yearLeft:
                        type: object
                        properties:
                          year:
                            type: integer
                            description: yearLeftで指定された年
                          oldAgeCount:
                            type: integer
                            description: 65歳以上の老年人口(人)
                          oldAgePercent:
                            type: number
                            description: 65歳以上の老年人口(パーセント)
                          middleAgeCount:
                            type: integer
                            description: 15歳～64歳の生産年齢人口(人)
                          middleAgePercent:
                            type: number
                            description: 15歳～64歳の生産年齢人口(パーセント)
                          newAgeCount:
                            type: integer
                            description: 0歳～14歳の年少人口(人)
                          newAgePercent:
                            type: number
                            description: 0歳～14歳の年少人口(パーセント)
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                class:
                                  type: string
                                  description: 年齢階級
                                man:
                                  type: integer
                                  description: 男性人口(人)
                                manPercent:
                                  type: number
                                  description: 男性人口(パーセント)
                                woman:
                                  type: integer
                                  description: 女性人口(人)
                                womanPercent:
                                  type: number
                                  description: 女性人口(パーセント)
                      yearRight:
                        type: object
                        properties:
                          year:
                            type: integer
                            description: yearRightで指定された年
                          oldAgeCount:
                            type: integer
                            description: '老年人口(人). 老年人口 : 65歳以上'
                          oldAgePercent:
                            type: number
                            description: '老年人口(パーセント). 老年人口 : 65歳以上'
                          middleAgeCount:
                            type: integer
                            description: '生産年齢人口(人). 生産年齢人口 : 15歳～64歳'
                          middleAgePercent:
                            type: number
                            description: '生産年齢人口(パーセント). 生産年齢人口 : 15歳～64歳'
                          newAgeCount:
                            type: integer
                            description: '年少人口(人). 年少人口 : 0歳～14歳'
                          newAgePercent:
                            type: number
                            description: '年少人口(パーセント). 年少人口 : 0歳～14歳'
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                class:
                                  type: string
                                  description: 年齢階級
                                man:
                                  type: integer
                                  description: 男性人口(人)
                                manPercent:
                                  type: number
                                  description: 男性人口(パーセント)
                                woman:
                                  type: integer
                                  description: 女性人口(人)
                                womanPercent:
                                  type: number
                                  description: 女性人口(パーセント)
      operationId: api.v1.population.composition.pyramid
      description: 地域単位、年単位の人口ピラミッドデータを返します。
      parameters:
        - $ref: '#/components/parameters/prefCode'
        - $ref: '#/components/parameters/cityCode'
        - schema:
            type: integer
            enum:
              - 1980
              - 1985
              - 1990
              - 1995
              - 2000
              - 2005
              - 2010
              - 2015
              - 2020
              - 2025
              - 2030
              - 2035
              - 2040
              - 2045
          in: query
          name: yearLeft
          description: 年度1(左側)
          required: true
        - schema:
            type: integer
            enum:
              - 1980
              - 1985
              - 1990
              - 1995
              - 2000
              - 2005
              - 2010
              - 2015
              - 2020
              - 2025
              - 2030
              - 2035
              - 2040
              - 2045
          in: query
          name: yearRight
          description: 年度2(右側)
          required: true
        - $ref: '#/components/parameters/addArea'
      x-internal: false
      tags:
        - 人口マップ / 人口構成
  /population/sum/perYear:
    get:
      summary: 人口増減率
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      line:
                        type: object
                        properties:
                          boundaryYear:
                            type: integer
                            description: 実績値と将来の推計値の区切り年
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                year:
                                  type: integer
                                  description: 年
                                value:
                                  type: number
                                  description: 総人口の比率
                      bar:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                year:
                                  type: integer
                                  description: 年
                                sum:
                                  type: number
                                  description: 総人口の比率（折れ線の総人口の比率と同じデータ）
                                class:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      label:
                                        type: string
                                        description: 老年人口 生産年齢人口 年少人口
                                      value:
                                        type: number
                                        description: 比率
      operationId: api.v1.population.sum.per_year
      tags:
        - 人口マップ / 人口増減
      description: 地域単位、年単位の人口増減率情報を返します。
      parameters:
        - $ref: '#/components/parameters/prefCode'
        - $ref: '#/components/parameters/cityCode'
        - $ref: '#/components/parameters/addArea'
  /population/sum/estimate:
    get:
      summary: 出生数・死亡数／転入数・転出数
      tags:
        - 人口マップ / 人口増減
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      boundaryYear:
                        type: integer
                        description: 実績値と推計値の区切り年
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                              description: ラベル + 総人口・転入数・転出数・出生数・死亡数
                            data:
                              type: array
                              items:
                                type: object
                                properties:
                                  year:
                                    type: integer
                                    description: 年
                                  value:
                                    type: integer
                                    description: 人口(千人)
      operationId: api.v1.population.sum.estimate
      description: 地域単位、年単位の出生数・死亡数／転入数・転出数の情報を返します。
      parameters:
        - $ref: '#/components/parameters/prefCode'
        - $ref: '#/components/parameters/cityCode'
        - $ref: '#/components/parameters/addArea'
  /population/nature:
    get:
      summary: 人口の自然増減
      tags:
        - 人口マップ / 人口の自然増減
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      line:
                        type: object
                        properties:
                          boundaryYear:
                            type: integer
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                yearRange:
                                  type: string
                                year:
                                  type: integer
                                value:
                                  type: number
                      bar:
                        type: object
                        properties:
                          boundaryYear:
                            type: integer
                          mandata:
                            type: array
                            items:
                              type: object
                              properties:
                                year:
                                  type: integer
                                value:
                                  type: integer
                          womandata:
                            type: array
                            items:
                              type: object
                              properties:
                                year:
                                  type: integer
                                value:
                                  type: integer
      operationId: api.v1.population.nature
      description: 地域単位、年単位の人口自然増減情報を返します。
      parameters:
        - $ref: '#/components/parameters/prefCode'
        - $ref: '#/components/parameters/cityCode'
        - schema:
            type: string
            enum:
              - '-'
              - '5'
              - '10'
              - '15'
              - '20'
              - '25'
              - '30'
              - '35'
              - '40'
              - '45'
              - '50'
              - '55'
              - '60'
              - '65'
              - '70'
              - '75'
              - '80'
              - '85'
            default: '-'
          in: query
          name: ageFrom
          description: 表示する年齢(開始)
        - schema:
            type: string
            default: '-'
            enum:
              - '-'
              - '4'
              - '9'
              - '14'
              - '19'
              - '24'
              - '29'
              - '34'
              - '39'
              - '44'
              - '49'
              - '54'
              - '59'
              - '64'
              - '69'
              - '74'
              - '79'
              - '84'
              - '89'
          in: query
          name: ageTo
          description: 表示する年齢(終了)
components:
  schemas: {}
  securitySchemes: {}
  parameters:
    addArea:
      name: addArea
      in: query
      required: false
      schema:
        type: string
        pattern: '^((([1-9]|[1-3][0-9]|4[0-7])_([0-9]{5})*)[,]?)+$'
      description: '追加エリアコード<br>他地域と合算した値を取得する際に使用するパラメータです。 「addArea=都道府県コード_市区町村コード」の形式で指定します。 複数指定する場合は「addArea=1_01100,13_13101」などのように、「,」 で各地域のパラメータを区切ります。 都道府県単位で指定する場合、「addArea=1_,13_」の形式で指定します。 最大10個指定でき、11個以上送られてきた場合はステータスコード400を返します。<br>「cityCode」で「すべての市区町村」(-)を選択した場合、addAreaで合算されるのは、都道府県単位の数値となります。 また、「cityCode」でいずれかの市区町村(13101など)を選択した場合、addAreaで合算されるのは、市区町村単位の数値となります。'
    prefCode:
      name: prefCode
      in: query
      required: true
      schema:
        type: integer
        minimum: 1
        maximum: 47
      description: 都道府県コード
    cityCode:
      name: cityCode
      in: query
      required: false
      schema:
        type: string
        pattern: '^([0-9]{5}|[-])$'
        default: '-'
      description: 市区町村コード
info:
  title: RESAS API
  description: RESAS API
  version: '1.0'
  contact:
    name: ot-nemoto
    url: 'https://github.com/ot-nemoto/resas-api/issues'
    email: nemoto@opentone.co.jp
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000/api/v1'
tags:
  - name: 人口マップ / 人口の自然増減
    description: 人口マップ / 人口の自然増減
  - name: 人口マップ / 人口構成
    description: 人口マップ / 人口構成
  - name: 人口マップ / 人口増減
    description: 人口マップ / 人口増減

