openapi: 3.0.0
paths:
  /prefectures:
    get:
      summary: 都道府県一覧
      tags:
        - 共通
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        prefCode:
                          type: integer
                          minimum: 1
                          maximum: 47
                        prefName:
                          type: string
                      required:
                        - prefCode
                        - prefName
                required:
                  - message
                  - result
      operationId: api.v1.common.prefectures
      description: 都道府県一覧
  /population/composition/perYear:
    parameters: []
    get:
      summary: 人口推移
      operationId: api.v1.population.composition.per_year
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    required:
                      - bundaryYear
                      - data
                    properties:
                      bundaryYear:
                        type: integer
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                              enum:
                                - 総人口
                                - 年少人口
                                - 生産年齢人口
                                - 老年人口
                            data:
                              type: array
                              items:
                                type: object
                                properties:
                                  year:
                                    type: integer
                                  value:
                                    type: integer
                                  rate:
                                    type: number
                                required:
                                  - year
                                  - value
                          required:
                            - label
                            - data
                required:
                  - message
                  - result
              examples: {}
      description: 人口推移
      parameters:
        - schema:
            type: integer
            minLength: 1
            maxLength: 47
            minimum: 1
            maximum: 47
          in: query
          name: prefCode
          description: 都道府県コード
          required: true
        - schema:
            type: string
            default: '-'
            pattern: '^([0-9]{5}|[-])$'
          in: query
          name: cityCode
          description: 市区町村コード
        - schema:
            type: string
            pattern: '^((([1-9]|[1-3][0-9]|4[0-7])_([0-9]{5})*)[,]?)+$'
          in: query
          name: addArea
          description: 追加エリアコード
      tags:
        - 人口マップ
        - 人口構成
  /population/composition/pyramid:
    get:
      summary: 人口ピラミッド
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    nullable: true
                  result:
                    type: object
                    properties:
                      yearLeft:
                        type: object
                        properties:
                          year:
                            type: integer
                          oldAgeCount:
                            type: integer
                          oldAgePercent:
                            type: number
                          middleAgeCount:
                            type: integer
                          middleAgePercent:
                            type: number
                          newAgeCount:
                            type: integer
                          newAgePercent:
                            type: number
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                class:
                                  type: string
                                man:
                                  type: integer
                                manPercent:
                                  type: number
                                woman:
                                  type: integer
                                womanPercent:
                                  type: number
                      yearRight:
                        type: object
                        properties:
                          year:
                            type: integer
                          oldAgeCount:
                            type: integer
                          oldAgePercent:
                            type: number
                          middleAgeCount:
                            type: integer
                          middleAgePercent:
                            type: number
                          newAgeCount:
                            type: integer
                          newAgePercent:
                            type: number
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                class:
                                  type: string
                                man:
                                  type: integer
                                manPercent:
                                  type: number
                                woman:
                                  type: integer
                                womanPercent:
                                  type: number
      operationId: api.v1.population.composition.pyramid
      description: 人口ピラミッド
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 47
          in: query
          name: prefCode
          description: 都道府県コード
          required: true
        - schema:
            type: string
            default: '-'
            pattern: '^([0-9]{5}|[-])$'
          in: query
          name: cityCode
          description: 市区町村コード
        - schema:
            type: integer
            enum:
              - 1980
              - 1985
              - 1990
              - 1995
              - 2000
              - 2005
              - 2010
              - 2015
              - 2020
              - 2025
              - 2030
              - 2035
              - 2040
              - 2045
          in: query
          name: yearLeft
          description: 年度1(左側)
          required: true
        - schema:
            type: integer
            enum:
              - 1980
              - 1985
              - 1990
              - 1995
              - 2000
              - 2005
              - 2010
              - 2015
              - 2020
              - 2025
              - 2030
              - 2035
              - 2040
              - 2045
          in: query
          name: yearRight
          description: 年度2(右側)
          required: true
        - schema:
            type: string
            pattern: '^((([1-9]|[1-3][0-9]|4[0-7])_([0-9]{5})*)[,]?)+$'
          in: query
          name: addArea
          description: 追加エリアコード
      x-internal: false
      tags:
        - 人口マップ
        - 人口構成
  /population/sum/perYear:
    get:
      summary: 人口増減率
      tags:
        - 人口マップ
        - 人口増減
      responses: {}
      operationId: api.v1.population.sum.per_year
components:
  schemas: {}
  securitySchemes: {}
info:
  title: RESAS API
  description: RESAS API
  version: '1.0'
  contact:
    name: ot-nemoto
    url: 'https://github.com/ot-nemoto/resas-api/issues'
    email: nemoto@opentone.co.jp
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000/api/v1'
tags:
  - name: 共通
  - name: 人口マップ
  - name: 人口構成
  - name: 人口増減
